"""add branch_id to categories

Revision ID: add_branch_id_cat
Revises: d4ef5d914c71
Create Date: 2025-11-22 13:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_branch_id_cat'
down_revision: Union[str, Sequence[str], None] = 'd4ef5d914c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop unique constraint on name since categories are now branch-specific
    op.drop_constraint('categories_name_key', 'categories', type_='unique')
    op.add_column('categories', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_categories_branch_id', 'categories', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_categories_branch_id', 'categories', type_='foreignkey')
    op.drop_column('categories', 'branch_id')
    # Restore unique constraint on name
    op.create_unique_constraint('categories_name_key', 'categories', ['name'])
    # ### end Alembic commands ###

